import {StyleSheet} from 'react-native';
import colors from '../../style/colors';
import dimensions from '../../style/dimensions';

const {ww} = dimensions;

export const styles = StyleSheet.create({
  body: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.s_,
    flexDirection: 'column',
    alignItems: 'stretch',
    alignContent: 'stretch',
  },
  header: {
    flex: 0,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingTop: 60,
    paddingBottom: 20,
  },
  headerContent: {
    paddingHorizontal: 20,
  },
  main: {
    flex: 2,
    backgroundColor: colors.shade,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 10,
  },
  close: {
    width: 40,
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  titulo: {
    fontFamily: 'AndaleMono',
    fontSize: 16,
    color: colors.white,
    fontWeight: 'bold',
  },
  ticket: {
    alignItems: 'center',
    paddingTop: 40,
  },
  periodoWrap: {
    marginTop: 6,
    marginLeft: -10,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 4,
    backgroundColor: colors.main,
    borderRadius: 20,
  },
  text: {
    fontFamily: 'AndaleMono',
    fontSize: ww <= 320 ? 12 : 13,
    color: colors.white,
    height: ww <= 320 ? 12 : 13,
  },
  label: {
    fontFamily: 'AndaleMono',
    fontSize: 10,
    color: colors.green,
    height: 12,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  detailsList: {
    padding: 10,
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    alignContent: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  eventosHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 10,
  },
  eventosHeaderLabel: {
    fontFamily: 'AndaleMono',
    fontSize: 14,
    color: colors.green,
    height: 16,
    textTransform: 'uppercase',
  },
  pill: {
    paddingHorizontal: 6,
    paddingTop: 6,
    paddingBottom: 2,
    borderRadius: 10,
    flexDirection: 'column',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: colors.green,
  },
  pillText: {
    fontFamily: 'AndaleMono',
    fontSize: 13,
    color: colors.main,
    height: 15,
  },
  eventosList: {
    borderTopColor: colors.bg,
    borderTopWidth: 1,
    marginTop: 10,
  },
  eventoWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    alignContent: 'stretch',
    padding: 10,
    borderBottomColor: colors.bg,
    borderBottomWidth: 1,
  },
  eventoIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    paddingHorizontal: 10,
    paddingTop: 4,
    paddingBottom: 4,
    marginRight: 10,
    backgroundColor: colors.bg,
    borderRadius: 20,
  },
  eventoIconText: {
    fontFamily: 'AndaleMono',
    fontSize: 13,
    color: colors.white,
    height: 13,
    marginLeft: 4,
    paddingTop: 2,
  },
  eventoCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    marginRight: 0,
  },
  eventoDesc: {
    flex: 1,
    paddingTop: 6,
  },
  spinner: {
    width: '100%',
    height: '100%',
    flex: 1,
    flexGrow: 1,
    // position: "absolute", zIndex: 20,
    marginTop: 30,
    paddingHorizontal: 40,
    flexDirection: 'column',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spinnerTitle: {
    fontFamily: 'AndaleMono',
    fontSize: 16,
    textAlign: 'center',
    color: colors.green,
    marginTop: 20,
  },
  spinnerText: {
    fontFamily: 'AndaleMono',
    fontSize: 14,
    textAlign: 'center',
    color: colors.white,
    marginTop: 5,
    lineHeight: 18,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  openButton: {
    marginTop: 12,
    backgroundColor: '#F194FF',
    borderRadius: 20,
    padding: 10,
    paddingLeft: 18,
    paddingRight: 18,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 4,
    textAlign: 'center',
    fontSize: 32,
    color: colors.greenHover,
    fontWeight: 'bold',
  },
  input: {
    marginTop: 20,
    borderRadius: 25,
    fontSize: 16,
    color: '#FFF',
    paddingHorizontal: 20,
    textAlign: 'center',
    backgroundColor: colors.main,
    marginBottom: 10,
    fontFamily: 'AndaleMono',
  },
  viewCategoria: {
    marginBottom: 20,
  },
  textCategoria: {
    fontSize: 30,
    fontWeight: 'bold',
    color: colors.p_,
  },
  itens: {
    padding: 10,
    borderRadius: 20,
  },
  card: {
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  cardTitle: {
    color: colors.p_,
  },
  cardSubTitle: {
    color: colors.p_light,
  },
  value: {
    color: colors.p_dark,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
